name: crypto
description: " currencies list application"

publish_to: 'none'

version: 3.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.19.0
  talker: ^4.4.0
  talker_dio_logger: ^4.4.0
  talker_bloc_logger: ^4.4.0
  json_annotation: ^4.9.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11




flutter:


  uses-material-design: true

  assets:
    - assets/


